/*********************************************************************************************************
Name            : MCFD_EntrFamilyCmpositionController_Test.cls  
Description     : Test class for MCFD_EnterFamilyCompositionController 
Created By      : Deloitte
Created Date    : 01/Mar/2017
Modification Log:
-------------------------------------------------------------------------------------------------------------- 
Developer       Date        Description
--------------------------------------------------------------------------------------------------------------            
Abhishek      01/Mar/2017   
--------------------------------------------------------------------------------------------------------------            
Vai				09/11/2017	Removing all the code as there is a new test class created
***************************************************************************************************************/

@isTest(seeAllData = false)
public class MCFD_EntrFamilyCmpositionController_Test{

   
}