/*********************************************************************************************************
Name            : MCFD_EnterFamilyCompositionContrlr_Test.cls  
Description     : This test class is used for covering all the test scneario 
                  related to the MCFD_EnterFamilyCompositionController class   
Created By      : Deloitte
Created Date    : 6/Feb/2017
Modification Log:
-------------------------------------------------------------------------------------------------------------- 
Developer       Date        Description
--------------------------------------------------------------------------------------------------------------            
Hemanth Manne  06/Feb/2017   
--------------------------------------------------------------------------------------------------------------            
***************************************************************************************************************/
@isTest(seeAllData=true)
public class MCFD_EnterFamilyCompositionContrlr_Test {
    /**
    * Method name  : testValidationScenarios
    * Description  : Use this method for testing SBC related classes
    * Return Type  : void
    * Parameter    : void
    **/
    /*
    private static testMethod void getContactInfoFromBackend(){
        Contact testCon = new Contact();
             testCon.FirstName='testFirstName';
             testCon.MiddleName='testMiddleName';
             testCon.LastName='testLastName';
             testCon.MCFD_Gender__c='male';
             testCon.Birthdate=system.today();
             testCon.Email='test@test.com';
             testCon.MCFD_SIN__c='999-999-999';
             testCon.MCFD_Marital_Status__c='Married, or living in a marriage-like relationship';
             testCon.MCFD_Govt_Disability_Benefit__c='yes';
             testCon.MCFD_Address_Check__c='yes';
             testCon.MCFD_SIN_Expiry_Date__c=system.today();
             testCon.MCFD_Primary_Phone_Number_Type__c='Home';
             testCon.MCFD_Secondary_Phone_Number_Type__c='work';
             testCon.MobilePhone='1234567890';
             testCon.Phone='1234567899';
        insert testCon;
        MCFD_EnterFamilyCompositionController.getContactInfoFromBackend(testCon.id);
    }
    */
}