/*********************************************************************************************************
Name            : MCFD_EstimatorChildData_Test.cls  
Description     : This test class is used for covering all the test scneario 
                  related to the MCFD_EstimatorChildData class   
Created By      : Deloitte
Created Date    : 15/06/2018
Modification Log:
-------------------------------------------------------------------------------------------------------------- 
Developer       Date        	Description
Liliana Trejo   15/06/2018   	Original Version
***************************************************************************************************************/
@isTest
public class MCFD_EstimatorChildData_Test {
    static testMethod void createData(){
        Test.startTest();
            //MCFD_EstimatorChildData.createData(1,true,'Test');
            //MCFD_EstimatorChildData.createData(1,null,'Test');
        Test.stopTest();
    }
    
}